<a href="https://colab.research.google.com/github/HyunPH/23-1_LA2/blob/main/%5B00%5D%EC%8B%A4%EC%8A%B5Zero.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
print("Hello world")

Hello world


라이브러리(패키지) 로드드

In [6]:
import numpy as np

프린트

In [11]:
def print_val(x):
  print("Type :", type(x))
  print("Shape :", x.shape)
  print("value:\n", x)
  print(" ")

In [14]:
x = np.array([1,2,3])
print_val(x)

x[0] = 5
print_val(x)

Type : <class 'numpy.ndarray'>
Shape : (3,)
value:
 [1 2 3]
 
Type : <class 'numpy.ndarray'>
Shape : (3,)
value:
 [5 2 3]
 


In [16]:
y = np.array([[1,2,3], [4,5,6]])
print_val(y)

Type : <class 'numpy.ndarray'>
Shape : (2, 3)
value:
 [[1 2 3]
 [4 5 6]]
 


In [17]:
a = np.zeros((2,2))
print_val(a)

Type : <class 'numpy.ndarray'>
Shape : (2, 2)
value:
 [[0. 0.]
 [0. 0.]]
 


In [18]:
a = np.ones((3,2))
print_val(a)

Type : <class 'numpy.ndarray'>
Shape : (3, 2)
value:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
 


단위 행렬(identity matrix)

In [22]:
a = np.eye(3,3)
print_val(a)

Type : <class 'numpy.ndarray'>
Shape : (3, 3)
value:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 


**랜덤행렬**

In [23]:
a = np.random.random((4,4))
print_val(a)

Type : <class 'numpy.ndarray'>
Shape : (4, 4)
value:
 [[0.59297487 0.46988811 0.19278455 0.58245636]
 [0.20939561 0.76910912 0.60333012 0.85050175]
 [0.87262148 0.2998489  0.37267887 0.11881891]
 [0.25978805 0.07578895 0.87404346 0.15542815]]
 


In [24]:
a = np.random.random((4,4))
print_val(a)

Type : <class 'numpy.ndarray'>
Shape : (4, 4)
value:
 [[0.07224855 0.58215219 0.78734589 0.84063548]
 [0.87948315 0.23120373 0.6616422  0.44475863]
 [0.52268073 0.80939161 0.76876191 0.43247892]
 [0.79945077 0.86394191 0.18336513 0.64309446]]
 


indexing

In [25]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print_val(a)

Type : <class 'numpy.ndarray'>
Shape : (3, 4)
value:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 


In [26]:
b = a[:2, 1:3]
print_val(b)

Type : <class 'numpy.ndarray'>
Shape : (2, 2)
value:
 [[2 3]
 [6 7]]
 


In [27]:
row1 = a[1, :]
print_val(row1)

Type : <class 'numpy.ndarray'>
Shape : (4,)
value:
 [5 6 7 8]
 


행렬 원소별 연산

In [28]:
m1 = np.array([[1,2], [3,4]], dtype = np.float64)
m2 = np.array([[5,6], [7,8]], dtype = np.float64)

In [30]:
print_val(m1 + m2)
print_val(np.add(m1, m2)) # add, sub, mul, div, sqrt, ...

Type : <class 'numpy.ndarray'>
Shape : (2, 2)
value:
 [[ 6.  8.]
 [10. 12.]]
 
Type : <class 'numpy.ndarray'>
Shape : (2, 2)
value:
 [[ 6.  8.]
 [10. 12.]]
 
